name: nlw_return
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  url_launcher: ^6.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Regular.ttf
    - family: Phosphor
      fonts:
        - asset: assets/fonts/Phosphor/Phosphor.ttf
  assets:
    - assets/images/Bug.png
    - assets/images/Idea.png
    - assets/images/Thought.png
    - assets/images/Success.png



