/// Flutter icons Phosphor
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Phosphor
///      fonts:
///       - asset: fonts/Phosphor.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Phosphor {
  Phosphor._();

  static const _kFontFam = 'Phosphor';
  static const String? _kFontPkg = null;

  static const IconData arrow_left = IconData(0xf282, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xf306, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_teardrop_dots = IconData(0xf338, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_notch = IconData(0xf347, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash = IconData(0xf602, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x = IconData(0xf642, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
